// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTqyZG8buuN23Kfb-C11_cN7Y9KtNCqL8',
    appId: '1:807023710093:android:15f2c4a8552bd1a7b777c4',
    messagingSenderId: '807023710093',
    projectId: 'flutter-chat-app-d7fb0',
    storageBucket: 'flutter-chat-app-d7fb0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0MXcyNaWBrKdsMbhlMMLSeWLFj2lP9Kg',
    appId: '1:807023710093:ios:9a27b590f7dd245ab777c4',
    messagingSenderId: '807023710093',
    projectId: 'flutter-chat-app-d7fb0',
    storageBucket: 'flutter-chat-app-d7fb0.appspot.com',
    androidClientId: '807023710093-7s5326vehuiqoiquihrgesigi251op27.apps.googleusercontent.com',
    iosClientId: '807023710093-ud4dqe79ae462dkf5qtrda57jab55hpu.apps.googleusercontent.com',
    iosBundleId: 'com.mobile.flutterApplication',
  );
}
